### PR TITLE
186 close open teamformation

### PR DESCRIPTION
**Pull request by hiddenmirage**
Create team formation task

### CODE REVIEW

**Comment by dinoboff** [comment]
> 
1,826 additions, 1,791 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

@hiddenmirage

Issue with white spaces?

**Comment by dinoboff** [comment]
ps: It will be pain to merge with upstream with PR.

**Comment by shiquan-lim** [comment]
@dinoboff @hiddenmirage 
Yes its a whitespace issue. Copy and pasted from firebase console.

**Comment by shiquan-lim** [comment]
@hiddenmirage please merge this branch with Amos' game show

**Pull request closed without merging**
